import "./globals.css";

export const metadata = {
  title: "Gustavo Gareis - Seguridad Electrónica",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body id="inicio">
        {children}
      </body>
    </html>
  );
}